### ISSUE TITLE
Getting it working in .mdx

### ISSUE THREAD

**Issue by jpzwarte** [ofhouse/storybook-stencil-example#2]
Hey,

First, thank you for writing the blog articles! Unfortunately, your articles are one of the few guides on how to get storybook working with stencil.

I'm trying to go one step further, use `.stories.mdx`. But i'm running into JSX problems.

```jsx
import { Meta, Preview, Story } from "@storybook/addon-docs/blocks";
import { h } from "jsx-dom";

<Meta title="My Component" />

# My Component

Hello world

<Preview>
  <Story name="API">
    {() => (
      <my-component
        first="Jeroen"
        middle="Pieter"
        last="Zwartepoorte"
      ></my-component>
    )}
  </Story>
</Preview>
```

Unfortunately, this does not work: 

```
Expecting an HTML snippet or DOM node from the story: "API" of "My Component".

Did you forget to return the HTML snippet from the story?
Use "() => <your snippet or node>" or when defining the story.
```

Any ideas/tips?

**Comment by jpzwarte** [comment]
I've got it working, trick was to use `@storybook/react` instead of `@storybook/html`.

I can now do:
```JSX
<Preview>
  <Story name="API">
    <my-component
      first="Jeroen"
      middle="Pieter"
      last="Zwartepoorte"
    ></my-component>
  </Story>
</Preview>
```

**Comment by ofhouse** [comment]
Hi,

that's a great idea to use it together with mdx!
Thanks for posting. I will take a look at the weekend to update & extend the examples here :+1: .
